# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
env:
  - NOT_CRAN=true
  - _R_CHECK_FORCE_SUGGESTS_: FALSE
install:
  - Rscript -e 'install.packages(c("remotes"));if (!all(c("remotes") %in% installed.packages())) { q(status = 1, save = "no")}'
  - Rscript -e 'remotes::install_github(c("r-lib/covr"))'
  - Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = c("Depends", "Imports", "LinkingTo"));if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
addons:
  apt:
    packages: cargo
after_success:
  - Rscript -e 'covr::codecov()'
