# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
env:
  - NOT_CRAN=true
r_github_packages:
  - r-lib/covr
before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'
after_success:
  - Rscript -e 'covr::codecov()'