# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
env:
  global:
    - NOT_CRAN=true
  matrix:
    - _R_CHECK_FORCE_SUGGESTS_: false
r_github_packages:
  - r-lib/covr
addons:
  apt:
    packages: cargo
after_success:
  - Rscript -e 'covr::codecov()'
